---
title: "slicing experiment"
output: html_notebook
---

# load packages
```{r}
library(tidyverse)
library(ggplot2)
library (ggthemes)
library(rstatix)
library(ggpubr)
library(emmeans)
library(dplyr)
```

# import & bind data
```{r}
## read sona and prolific data

prolific_data <- read_csv('data/prolific_data.csv')
sona_data <- read_csv('data/sona_data.csv') 

ncol(prolific_data)
ncol(sona_data)

colnames(prolific_data)
colnames(sona_data)

## remove extra col.
sona_data <- sona_data %>% select(!c(sona_id))

##bind prolific & sona data
data <- rbind(prolific_data, sona_data)
```

# basic descriptives
```{r}
## N(initial)
data %>% pull(subject) %>% unique()

## number of trials per subject
data %>% group_by(subject) %>% count()

### caution: subject 'NA'
```

# filtering and accuracy exclusion
```{r}
##exclude filler, practice, and non-picture trials
data <- data %>% filter(typeoftrial=="picture" & !(trialcondition %in% c("filler", "practice")))

##calculate subject accuracy
data <- data %>% mutate(accuracy=ifelse(correct=="TRUE",1,0))

subject_accuracy <- data %>% group_by(subject) %>%
      summarise(TaskAccuracy=mean(accuracy))

##exclude incorrect responses
data = data %>% filter(accuracy==1)

##exclude subjects with accuracy < 60% & incorrect responses
InaccurateSubjects <- subject_accuracy %>% filter(TaskAccuracy < 0.6)

data2 = data %>% filter(!subject %in% InaccurateSubjects$subject) 

##total participants after exclusion: N=48
data2 %>% pull(subject) %>% unique()
```

# log10 transformation & histograms
```{r}
data2 <- data2 %>% mutate(rt = as.numeric(rt)) %>% mutate(log10_rt=log(rt, 10))

data2 %>% filter(rt <10000) %>% ggplot(aes(x=rt)) + geom_histogram(binwidth =20, fill="pink" ) + theme_economist() + labs(x="RT (ms)", y="frequency", title= "RT histogram")

data2 %>% ggplot(aes(x=log10_rt)) + geom_histogram(binwidth =0.1, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")
```

# subject means
```{r}
subject_means <- data2 %>% group_by(subject, trialcondition) %>% summarise(subj_mean=mean(log10_rt))
```


# outliers
```{r}
outliers <- subject_means %>% group_by(trialcondition) %>% identify_outliers(subj_mean)
```

