---
title: "typicality experiment"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# load packages
```{r}
library(tidyverse)
library(ggplot2)
library (ggthemes)
library(rstatix)
library(ggpubr)
library(emmeans)
library(dplyr)
setwd(here::here())
getwd()
```

# import & bind data
```{r}
## compile data for each sona/prolific subject into 2 files
P_subjects = list.files(path ='../data/prolific', recursive = TRUE, pattern = '.csv', full.names = TRUE)
prolific_data <- read_csv(P_subjects) %>% rbind()

S_subjects = list.files(path ='../data/sona', recursive = TRUE, pattern = '.csv', full.names = TRUE)
sona_data <- read_csv(S_subjects) %>% rbind()

## import 2nd prolific data file
prolific2 <- read_csv("../data/typicality.csv")

## merge sona and prolific data
ncol(prolific_data)
ncol(sona_data)
ncol(prolific2)
colnames(prolific2)
colnames(prolific_data)

prolific2 <- prolific2 %>% select(!(c(12:22)))

data <- rbind(prolific_data, sona_data, prolific2) %>% filter(!is.na(subject))
```

# basic descriptives
```{r}
## N(initial) = 70
length(data %>% pull(subject) %>% unique())

## number of trials per subject
View(data %>% group_by(subject) %>% count())
```
# data treatment

## exclusions
```{r}
##exclude filler, practice, and non-picture trials
exclusions_data <- data %>%
  filter(typeoftrial=="picture" & !(trialcondition %in% c("filler", "practice"))) %>%
  filter(List != "practice")%>%
  ##calculate subject accuracy
  mutate(accuracy=ifelse(correct=="TRUE",1,0)) %>% 
  separate(trialcondition, into = c("typicality", "state"))
```

# accuracy analyses

##accuracy data
```{r}
subject_accuracy <- exclusions_data %>% group_by(subject) %>% summarise(TaskAccuracy=mean(accuracy))
InaccurateSubjects <- subject_accuracy %>% filter(TaskAccuracy < 0.78)
```

## plot
```{r}
exclusions_data %>% 
  group_by(typicality, state) %>%
   summarise(ci = list(mean_cl_boot(accuracy) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest%>%
  mutate(state = fct_recode(state, canonical = "whole", `non-canonical` = "slice" ),
         state = fct_relevel(state, "non-canonical","canonical"))%>%
  ggplot(aes(x= state, y = mean, group = typicality, fill = typicality)) +
geom_bar(stat = "identity", position = "dodge", width = 0.7, color = "gray24")+
  geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.15, 
                color = "black", position = position_dodge(0.70))+
  labs(y = "mean accuracy", title = "squashability ratings")+
  theme_clean()+
  scale_fill_manual(values = c("darksalmon", "darkslategray4"))+
  theme(plot.background = element_rect(
    color = "white"),
    strip.text.x = element_text(size =rel(2)),
        axis.text = element_text(size =rel(1.5)),
        axis.title = element_text(size =rel(2)),
        plot.title = element_text(hjust = .5, size = rel(1.5)))
```
## main accuracy model
```{r}
library(glmmTMB)
library(lme4)
acc_model = glmer(data = exclusions_data, 
                  accuracy ~ state*typicality + (1 + state*typicality|subject) + (1|stimulus),
                  family = "binomial", 
                 control = glmerControl(optimizer = "bobyqa",
                                         optCtrl=list(maxfun=200000), 
                      check.conv.singular = .makeCC(action = "ignore",  tol = 1e-4)))
summary(acc_model)
car::Anova(acc_model)

sjPlot::plot_model(acc_model, type = "int")
```

No interaction but significant effect of typicality

# RT analyses

## rt data
```{r}
##exclude incorrect responses
rt_data <- exclusions_data %>% filter(accuracy==1) %>%
  ##exclude subjects with accuracy < 80%
  filter(!subject %in% InaccurateSubjects$subject)

##total participants after exclusion: N = 60 
length(rt_data %>% pull(subject) %>% unique())
```


## transforming RT
```{r}
##make rt numeric
rt_data <- rt_data %>% mutate(rt = as.numeric(rt))
## rt histogram ----does NOT look normally distributed (positive skew)
rt_data %>% filter(rt <10000) %>% 
  ggplot(aes(x=rt)) + geom_histogram(binwidth =20, fill="pink" ) + 
  theme_economist() + labs(x="RT (ms)", y="frequency", title= "RT histogram")

##rt log (base 10) transformation
rt_data <- rt_data %>% mutate(log10_rt=log(rt, 10))

##log10(rt) histogram
rt_data %>% 
  ggplot(aes(x=log10_rt)) + geom_histogram(binwidth =0.1, fill="pink" ) + 
  theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")
```

## MAD exclusions
```{r}
mad_data = rt_data %>%
  group_by(typicality, state) %>%
  mutate(MAD=3*mad(log10_rt), med=median(log10_rt),
         L= (med - MAD), U=(med + MAD)) %>%
  filter(log10_rt < U) %>% filter(log10_rt > L)

(nrow(rt_data)-nrow(mad_data))/nrow(rt_data)
```

## plot
```{r}
mad_data %>% 
  group_by(typicality, state) %>%
   summarise(ci = list(mean_cl_boot(rt) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest%>%
  mutate(state = fct_recode(state, canonical = "Intact", `non-canonical` = "Smashed" ),
         state = fct_relevel(state, "non-canonical","canonical"))%>%
  ggplot(aes(x= state, y = mean, group = typicality, fill = typicality)) +
geom_bar(stat = "identity", position = "dodge", width = 0.7, color = "gray24")+
  geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.15, 
                color = "black", position = position_dodge(0.70))+
  labs(y = "RT (ms)", title = "RT per squashability x state condition")+
  theme_clean()+
  scale_fill_manual(values = c("black", "lightgray"))+
  theme(plot.background = element_rect(
    color = "white"),
    strip.text.x = element_text(size =rel(2)),
        axis.text = element_text(size =rel(1.5)),
        axis.title = element_text(size =rel(2)),
        plot.title = element_text(hjust = .5, size = rel(1.5)))
```

## main RT model
```{r}
rt_model = lmer(data = mad_data, 
                log10_rt ~ typicality*state +
                  (1 + typicality*state |subject) + (1|stimulus),
                REML = FALSE, 
                control = lmerControl(optimizer ='optimx', optCtrl=list(method='nlminb'),
                    check.conv.singular = .makeCC(action = "ignore",  tol = 1e-4)))
summary(rt_model)
car::Anova(rt_model)
```

Significant main effect of typicality and state. No interaction.

### assumptions
```{r}
library(glmmTMB)
sjPlot::plot_model(rt_model, type='diag')
sjPlot::plot_model(rt_model, type='resid')
```

# Demographic Info
```{r}
demo = data %>% filter(typeoftrial %in% c("demo", "english") & response != "0") %>%
  separate(response, into = c("demo1", "demo2", "demo3", "demo4"), sep = ":")
age = demo %>% filter(demo1 == "{\"Age\"") %>% select(demo2) %>%
  mutate(age = as.numeric(gsub("[^[:digit:] ]", "", demo2)))
age %>% summarise(mean_age = mean(age))
race = demo %>% filter(demo1 == "{\"Race\"") %>% select(demo2)
race %>% group_by(demo2) %>% count()
gender_education = demo %>% filter(demo1 == "{\"Age\"") %>% select(demo3) %>%
  separate(demo3, into = c("gender", "education"), sep = ",")  %>%
  mutate(gender = tolower(gender),
         gender = gsub("[[:space:]]", "", gender))
gender_education %>% group_by(gender) %>%
  count()
gender_education %>% group_by(education) %>%
  count()
first_lang = demo %>% filter(demo1 == "{\"English\"") %>% select(demo2)
first_lang %>% group_by(demo2) %>% count()
```

```{r}
"18-19" =(age %>% filter(c(age) <= 19 & c(age) >= 18) %>% count())
"20-29" = (age %>% filter(c(age) <= 29 & c(age) >= 20) %>% count())
"30-39" = (age %>% filter(c(age) <= 39 & c(age) >= 30) %>% count())
"40-49" = age %>% filter(c(age) <= 49 & c(age) >= 40) %>% count()
"50-59" = (age %>% filter(c(age) <= 59 & c(age) >= 50) %>% count())
"60+" = (age %>% filter(c(age) >= 60) %>% count())

```


