---
title: "state_change_power_analysis"
author: "Channing Hambric"
date: "2024-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library (ggthemes)
library(rstatix)
library(ggpubr)
library(emmeans)
library(dplyr)
library(stats)
library(lmerTest)
library(simr)
library(optimx)
library(pwr)
setwd(here::here())
getwd()
```

```{r}
## read data
data1 <- read_csv('../data/preregistered.csv') %>% mutate(data_source = "preregistered")
data2 <- read_csv('../data/unregistered.csv') %>% mutate(data_source = "unregistered")

data = rbind(data1 %>% select(subject, typeoftrial, response, stimulus, rt,
                               trialcondition, index, correct, comprehension_type, 
                               Experiment, question_order, data_source, time_elapsed), 
              data2 %>% select(subject, typeoftrial,response, rt, stimulus, 
                                trialcondition, index, correct, comprehension_type, 
                                Experiment, question_order, data_source, time_elapsed)) %>% 
                        filter(!is.na(subject))

## USE THIS CODE TO EXAMINE ONE DATASET AT A TIME
 data  = data %>% filter(data_source == "preregistered")  ### preregistered
# data  = data %>% filter(data_source == "unregistered")  ### unregistered
  
ncol(data)
colnames(data)
```

```{r}
lang <- data %>% filter(typeoftrial == "notenglish") %>% 
  separate(response, into = c("first", "age"), sep = ",") %>% 
  separate(first, into = c("q0", "first"), sep = ":") %>% mutate(first = gsub(" ", "", first)) %>%
  filter(toupper(first) != '"ENGLISH"')

data <- data %>% filter(!subject %in% lang$subject)
```


```{r}
comprehension_scores <- data %>% group_by(data_source, subject) %>%
  filter(typeoftrial=="comprehension") %>% count(response==comprehension_type) %>%
  pivot_wider(names_from = c(3), values_from = n) %>% rename(correct = "TRUE") %>% 
  rename(incorrect = "FALSE") %>% mutate(comp = case_when(data_source == "unregistered" ~ incorrect /24,
                                                          .default = correct /24))
# For the unregistered data, comprehension responses were labeled 'incorrect' when they were actually 'correct' (and vice-versa). To address this, the code now calculates the comp.score by dividing incorrect/24 for the unregistered data: see the case_when() code above.

inaccurate_comp <- comprehension_scores %>% filter(comp < 0.5)
```


```{r}
##exclude filler, practice, and non-picture trials
exclusions_data <- data %>% 
  filter(typeoftrial=="picture" & !(trialcondition %in% c("filler", "practice", "practice_n", "practice_s"))) %>%
  ##exclude bad comprehension
  filter(!subject %in% inaccurate_comp$subject) %>%
  separate(trialcondition, into = c("weight", "state")) 
```


```{r}
##exclude incorrect responses
rt_data <- exclusions_data %>% filter(correct==1) %>%
  ##exclude subjects with accuracy < 80%
  filter(!subject %in% InaccurateSubjects$subject)

length(rt_data %>% pull(subject) %>% unique())
```


```{r}
rt_data <- rt_data %>% mutate(rt = as.numeric(rt)) %>% mutate(log10_rt=log(rt, 10))

mad_data = rt_data %>%
  group_by(weight, state) %>%
  mutate(MAD=3*mad(log10_rt), med=median(log10_rt),
         L= (med - MAD), U=(med + MAD)) %>%
  filter(log10_rt < U) %>% filter(log10_rt > L)

(nrow(rt_data)-nrow(mad_data))/nrow(rt_data)

length(mad_data %>% pull(subject) %>% unique())
```


```{r}
rt_model_with_interaction = lmer(data = mad_data, 
                log10_rt ~ weight*state + (1 + weight*state |subject) + (1|stimulus),
                REML = FALSE, 
                lmerControl(optimizer = "bobyqa",
                            optCtrl=list(maxfun=200000),
                    check.conv.singular = .makeCC(action = "ignore",  tol = 1e-4)))
summary(rt_model_with_interaction)
car::Anova(rt_model_with_interaction)

rt_model_no_interaction = lmer(data = mad_data, 
                log10_rt ~ weight + state + (1 + weight + state |subject) + (1|stimulus),
                REML = FALSE, 
                control = lmerControl(optimizer ='optimx', optCtrl=list(method='nlminb'),
                    check.conv.singular = .makeCC(action = "ignore",  tol = 1e-4)))
summary(rt_model_no_interaction)
car::Anova(rt_model_no_interaction)

anova(rt_model_no_interaction, rt_model_with_interaction)
```


#POWER ANALYSIS

```{r}
# Simulate some example data
n <- 250  #number of participants
data <- expand.grid(Subject = factor(1:n),
                    A = factor(c("A1", "A2")),
                    B = factor(c("B1", "B2")),
                    C = factor(c("C1", "C2")))
set.seed(123)
data$DV <- rnorm(nrow(data), mean=0, sd=1)

# Fit the mixed-effects model
model <- lmer(DV ~ A * B * C + (1|Subject), data = data)

# Adjust the effect size for lowest level interaction term
fixef(model)["AA2:BB2:CC2"] <- 0.5 
power_sim <- powerSim(model, test = fixed("AA2:BB2:CC2", "t"), nsim = 1000)

print(power_sim)

#80% power @ 250 p's
```







