---
title: "Survey Cleaning"
author: "Channing Hambric"
date: "2025-03-23"
output: html_document
---

## Packages
```{r}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(dplyr)
library(ggthemes)
library(ggplot2)
library(stringr)
library(paletteer)
library(patchwork)
library(lme4)
library(lmerTest)
library(tidyboot)
library(emmeans)
```


#ENGLISH

## Import Data
```{r}
data <-read.csv("../data/Object_State_Survey_Prolific_English.csv", fileEncoding = "UTF-8")
```

## Qualtrics data cleaning & reorganization
```{r}
# Remove second row (filled with Qualtrics misc)
data <- data[-c(2), ] %>%rename(id="PROLIFIC_PID")

# Grab demographic columns
demos <- data %>%
  select(Age, Gender, Race, Hispanic, NES, EngAOA,NativeLang) %>%
  slice(-1)

# Move 'id' to the first column and delete demos
pre_clean_data <- data %>% relocate(id, .before = everything()) %>% select(-matches("Practice")) %>% select(-c(Age, Gender, Race, Hispanic, NES, NativeLang))



#Setting Up Rating Data
rating_data <- pre_clean_data %>%
  select(1, matches("_Before_|_After_|_Imply_")) %>%
  slice(-1) %>%
  pivot_longer(cols = -1,  
               names_to = "Condition",  
               values_to = "Score") %>%
  separate(Condition, 
           into = c("verb", "tense", "target_object", "question", "focus", "extra"), 
           sep = "_", 
           fill = "right") %>%
  select(-extra) %>%
  mutate(Score = na_if(Score, "")) %>%  
  mutate(Score = na_if(Score, " ")) %>% 
  drop_na(Score) %>%
  mutate(
    verb = recode(verb, "D" = "Drop", "C" = "Contact"),
    tense = recode(tense, "Pr" = "Present", "Pa" = "Past"),
    target_object = recode(target_object, "T" = "tomato", "B" = "Blueberry", "M" = "muffin"),
    focus = recode(focus, "NF" = "NotFocus", "F" = "Focus"),
    focus = recode(focus, "1" = "NA"),
    Score = as.numeric(Score),id= as.factor(id)) #make id factor

#Setting Up Ranking Data
ranking_data <- pre_clean_data %>%
  select(1, matches("_Rank_"))  

# Extract ranked objects from question text
new_names <-ranking_data %>%select(-1)%>%
  slice(1) %>%  # Select the first row
  unlist() %>%  # Convert to vector
  str_split(" - ", simplify = TRUE) %>%  # Split by " - "
  .[, 2]  # Get the word after the hyphen

# Replace numeric suffix in column names with extracted objects
colnames(ranking_data)[-1] <- str_replace(colnames(ranking_data)[-1], "\\d+$", new_names)

# Separate out conditions
ranking_data <- ranking_data %>% 
  slice(-1) %>%
  pivot_longer(cols = -1,  
               names_to = "Condition",  
               values_to = "Ranking") %>% 
  mutate(Ranking = na_if(Ranking, "")) %>%  
  mutate(Ranking = na_if(Ranking, " ")) %>% 
  drop_na(Ranking) %>%
  mutate(Condition_type = ifelse(str_starts(Condition, "C"), "C", "D"))  # Identify if drop or contact verb

# Separate out contact conditions (incl focus)
c_conditions <- ranking_data %>%
  filter(Condition_type == "C") %>%
  separate(Condition, 
           into = c("verb", "tense", "target_object", "question", "focus", "ranked_object"), 
           sep = "_", 
           fill = "right")

# Separate out drop conditions
d_conditions <- ranking_data %>%
  filter(Condition_type == "D") %>%
  separate(Condition, 
           into = c("verb", "tense", "target_object", "question", "ranked_object"), 
           sep = "_", 
           fill = "right") %>%
  mutate(focus = NA)  # Set focus to NA for 'D' conditions

# Combine the results
ranking_data <- bind_rows(c_conditions, d_conditions) %>%
  select(-Condition_type) %>% 
  mutate(
    verb = recode(verb, "D" = "Drop", "C" = "Contact"),
    tense = recode(tense, "Pr" = "Present", "Pa" = "Past"),
    target_object = recode(target_object, "T" = "tomato", "B" = "Blueberry", "M" = "muffin"),
    focus = recode(focus, "NF" = "NotFocus", "F" = "Focus")
  ) %>% 
  filter(!is.na(Ranking) & str_trim(Ranking) != "") %>%
  mutate(ranked_object_recoded = recode(ranked_object,
                                "the muffin" = "target object",
                                "the tomato" = "target object",
                                "the blueberry" = "target object",
                                "the brick" = "falling object",
                                "the bowling ball" = "falling object"))  


#N check
rating_data %>% group_by(id) %>% count()
ranking_data %>% group_by(id) %>% count()

#write clean data to csv
write.csv(rating_data,"rating_data_english.csv")
write.csv(ranking_data,"ranking_data_english.csv")

```

#PORTUGUESE

## Import Data
```{r}
data_pg <-read.csv("../data/Object_State_Survey_Prolific_PG.csv", fileEncoding = "UTF-8") %>%rename("id"="PROLIFIC_PID")
```

## Cleaning
```{r}

# Remove second row (assuming it's unwanted)
data_pg <- data_pg[-c(2), ]

# Select demographic columns
demos_pg <- data_pg %>%
  select(id,Age, Gender, Race, Hispanic, NES, PGAOA,NativeLang) %>%
  slice(-1)

# Move 'id' to the first column and delete demos
pre_clean_data_pg <- data_pg%>% relocate(id, .before = everything()) %>% select(-matches("Practice")) %>% select(-c(Age, Gender, Race, Hispanic, NES, NativeLang))


#Below will need to be changed for PG (adding null sub condition)
#Setting Up Rating Data
rating_data_pg <- pre_clean_data_pg %>%
  select(1, matches("_Before_|_After_|_Imply_")) %>%
  slice(-1) %>%
  pivot_longer(cols = -1,  
               names_to = "Condition",  
               values_to = "Score")%>%
  mutate(copy=Condition)%>%
  separate(Condition, 
           into = c("verb", "tense", "target_object"), 
           sep = "_", 
           fill = "right") %>%
  mutate(Score = na_if(Score, "")) %>%  
  mutate(Score = na_if(Score, " ")) %>% 
  drop_na(Score) %>%
  mutate(
    verb = recode(verb, "D" = "Drop", "C" = "Contact"),
    tense = recode(tense, "Pr" = "Present", "Pa" = "Past"),
    target_object = recode(target_object, "T" = "tomato", "B" = "Blueberry", "M" = "muffin"),
    Score = as.numeric(Score)  # Convert Score to numeric scale
  )

d_qs <- rating_data_pg %>%
  filter(verb == "Drop") %>%
  separate(copy, 
           into = c("verb", "tense", "target_object", "question", "subject","extra"), 
           sep = "_", 
           fill = "right") %>%
  mutate(focus = NA)  # Set focus to NA for 'D' conditions

c_qs <- rating_data_pg %>%
  filter(verb == "Contact") %>%
  separate(copy, 
           into = c("verb", "tense", "target_object", "question", "focus","extra"), 
           sep = "_", 
           fill = "right") 

rating_data_pg <- bind_rows(d_qs, c_qs) %>% select(-extra)%>%mutate(
    verb = recode(verb, "D" = "Drop", "C" = "Contact"),
    tense = recode(tense, "Pr" = "Present", "Pa" = "Past"),
    target_object = recode(target_object, "T" = "tomato", "B" = "Blueberry", "M" = "muffin"),
    focus = recode(focus, "NF" = "NotFocus", "F" = "Focus"),subject = recode(subject, "N" = "Null", "V" = "Explicit"))

#Setting Up Ranking Data
ranking_data_pg <- pre_clean_data_pg %>%
  select(1, matches("_Rate_"))  

# Extract ranked objects
new_names_pg <-ranking_data_pg %>%select(-1)%>%
  slice(1) %>%  # Select the first row
  unlist() %>%  # Convert to vector
  str_split(" - ", simplify = TRUE) %>%  # Split by " - "
  .[, 2]  # Get the second part after the hyphen

# Replace numeric suffix in column names with extracted objects
colnames(ranking_data_pg)[-1] <- str_replace(colnames(ranking_data_pg)[-1], "\\d+$", new_names_pg)

# Separate out conditions
ranking_data_pg <- ranking_data_pg %>% 
  slice(-1) %>%
  pivot_longer(cols = -1,  
               names_to = "Condition",  
               values_to = "Ranking") %>% 
  mutate(Ranking = na_if(Ranking, "")) %>%  
  mutate(Ranking = na_if(Ranking, " ")) %>% 
  drop_na(Ranking) %>%
  mutate(Condition_type = ifelse(str_starts(Condition, "C"), "C", "D"))  # Identify if drop or contact verb

# Separate contact conditions
c_conditions_pg <- ranking_data_pg %>%
  filter(Condition_type == "C") %>%
  separate(Condition, 
           into = c("verb", "tense", "target_object", "question", "focus", "ranked_object"), 
           sep = "_", 
           fill = "right")%>%
  mutate(subject = NA)

# Separate drop conditions
d_conditions_pg <- ranking_data_pg %>%
  filter(Condition_type == "D") %>%
  separate(Condition, 
           into = c("verb", "tense", "target_object", "question","subject", "ranked_object"), 
           sep = "_", 
           fill = "right") %>%
  mutate(focus = NA)  # Set focus to NA for 'D' conditions

# Combine the results
ranking_data_clean_pg <- bind_rows(c_conditions_pg, d_conditions_pg) %>%
  select(-Condition_type) %>% 
  mutate(
    verb = recode(verb, "D" = "Drop", "C" = "Contact"),
    tense = recode(tense, "Pr" = "Present", "Pa" = "Past"),
    target_object = recode(target_object, "T" = "tomato", "B" = "Blueberry", "M" = "muffin"),
    focus = recode(focus, "NF" = "NotFocus", "F" = "Focus"),
    subject = recode(subject, "N" = "Null", "V" = "Explicit") 
  ) %>% 
  filter(!is.na(Ranking) & str_trim(Ranking) != "") %>%
  mutate(
    ranked_object_recoded = recode(ranked_object,
      "the muffin" = "target object",
      "the tomato" = "target object",
      "the blueberry" = "target object",
      "the brick" = "falling object",
      "the bowling ball" = "falling object"))


#N check
rating_data_pg %>% group_by(id) %>% count()
ranking_data_clean_pg %>% group_by(id) %>% count()

#write clean data to csv
write.csv(rating_data_pg,"rating_data_portuguese.csv")
write.csv(ranking_data_clean_pg,"ranking_data_portuguese.csv")


```



