---
title: "Norming Analysis"
output: html_document
date: "2025-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
library(tidyverse)
library(purrr)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(tidyboot)
library(paletteer)
library(lme4)
library(emmeans)
library(knitr)
library(patchwork)
library(data.table)
library(dplyr)
library(gt)
library(ggrepel)
```


# Import Data
```{r}
data <-read.csv("../data/object-state-norming.csv", fileEncoding = "UTF-8")

demos <- data %>% filter(typeoftrial %in% c("demo","english","notenglish"))%>%
  select(subject,age, gender, education,race, hispanic, dominantHand, alert, english, age_learned_english) 

non_nes<-demos%>%filter(age_learned_english>4)%>%select(subject)


obj_clean <- data %>% filter(!subject %in% non_nes$subject)%>%
  select(subject, state, exp_number, sentence, object,response) %>%
  filter(state != "")%>%filter(response!=" ")%>%mutate(response=as.numeric(response))

sentence_clean<-data %>%filter(!subject %in% non_nes$subject)%>%
  select(subject,sentence,sentence_condition,target, Q1,Q2,Q3,A1,A2,A3,Apos1_label,Apos2_label,Apos3_label)%>%filter(sentence_condition!="")%>%mutate(Q1=as.numeric(Q1),Q2=as.numeric(Q2),Q3=as.numeric(Q3))


sentence_clean %>% group_by(subject) %>%count()
# N=64 (3 dropped for lang)
```


# Object Norming
```{r}
#smashed_covariates<-obj_clean%>%filter(state=="Smashed")%>%
#  group_by(state,object)%>%
#  summarise(
 #   mean_rating=mean(response))

#write.csv(smashed_covariates, "smashed_covariates.csv")

#sliced_covariates<-obj_clean%>%filter(state=="Slice")%>%
##  group_by(state,object)%>%
#  summarise(
 #   mean_rating=mean(response))

#write.csv(sliced_covariates, "sliced_covariates.csv")

#on average,  is there a difference between how canonical p's considered sliced vs whole objects 
slice_model<-lmer(data=obj_clean %>%filter(state!="Smashed"),response~state + (1|subject) + (1|object))
summary(slice_model)
car::Anova(slice_model)

# whole items considered significantly more typical/canonical

```

# Sentence Norming
```{r}
#First looking at Q1-3

#Q1: Before...
#Q2: After...
#Q3 : Does the sentence imply..
# reformatting Q4 (prominence q)

sentence_long <- sentence_clean %>%
  rename(
    answer_1 = A1, answer_2 = A2, answer_3 = A3,
    label_1  = Apos1_label, label_2  = Apos2_label, label_3  = Apos3_label
  ) %>%
  pivot_longer(
    cols = matches("^(answer|label)_[123]$"),
    names_to   = c(".value", "pos"),   # create 'answer' and 'label' columns
    names_sep  = "_"
  ) %>%
  mutate(pos = paste0("A", pos)) %>%   # A1/A2/A3
  select(subject, sentence_condition,target,pos, answer, label) %>%
  mutate(
    label_recoded = case_when(
      label %in% c("blueberry", "muffin", "tomato") ~ "target object",
      label %in% c("bowling ball","falling brick") ~ "falling object", TRUE~label))%>%filter(label!="null")


#Q1 - Do sentences differ in what they imply to be the initial state of the object
q1_model<-lm(data=sentence_clean,Q1~sentence_condition)
summary(q1_model)

#As expected no meaningful differences

#Q2 - Do sentences differ in what they imply to be the final state of the object
q2_model<-lm(data=sentence_clean,Q2~sentence_condition)
summary(q2_model)

q2_4_comp <- lm(
  Q2 ~ sentence_condition,
  data = sentence_clean %>%
    filter(sentence_condition %in% c(
      "E1",
      "4a-Focus","4a-NotFocus",
      "4c-Focus","4c-NotFocus",
      "R2-Focus","R2-NotFocus")) %>%
    mutate(sentence_condition = relevel(factor(sentence_condition), ref = "E1")))
summary(q2_4_comp)


#The 4a-Focus condition was rated significantly lower than 4a-NotFocus, 4c-Focus, 4c-NotFocus, R2-Focus, and R2-NotFocus

#Q3 - Do sentences differ in how much they imply the action
q3_model<-lm(data=sentence_clean,Q3~sentence_condition)
summary(q3_model)

q3_4_comp <- lm(
  Q3 ~ sentence_condition,
  data = sentence_clean %>%
    filter(sentence_condition %in% c(
      "E1",
      "4a-Focus","4a-NotFocus",
      "4c-Focus","4c-NotFocus",
      "R2-Focus","R2-NotFocus")) %>%
    mutate(sentence_condition = relevel(factor(sentence_condition), ref = "E1")))
summary(q3_4_comp)

#Overall, Experiment 1, Experiment 2, & Experiment 4c (both Focus and Not Focus conditions) most strongly implied state change. Sentences from Experiment 4a did not differ across Focus conditions, and implication ratings were similar to sentences suggested by Reviewer 2, with the exception that the not focus sentences suggested by Reviewer 2 implied more state change. 

#The 4a-Focus condition did not significantly differ from 4a-NotFocus or R2-Focus, but was rated significantly lower than 4c-Focus, 4c-NotFocus,and R2-NotFocus

#Q4 - Are different target objects rated more or less prominent across different sentence conditions

exp_order_focus<- c("E1","4a-Focus","4a-NotFocus","4c-Focus","4c-NotFocus","R2-Focus","R2-NotFocus")
sentence_long_order_focus<-sentence_long%>%mutate(sentence_condition = factor(sentence_condition, levels = exp_order_focus))%>%filter(sentence_condition!="NA")


q4_model <- lm(
  answer ~ sentence_condition*label_recoded,
  data = sentence_long_order_focus %>%
    filter(sentence_condition %in% c(
      "E1",
      "4a-Focus","4a-NotFocus",
      "4c-Focus","4c-NotFocus",
      "R2-Focus","R2-NotFocus")) %>%
    mutate(sentence_condition = relevel(factor(sentence_condition), ref = "E1")))
summary(q4_model)

#Overall, the falling object was most prominent in Experiment 4a Not Focus condition, followed by 4a Not Focus condition. The target object was most prominent in Experiment 4a - Focus and Not Focus conditions  (roughly equally so), though differences were minimal across #conditions.

#So in other words, in the sentences without "you" as a third noun (Experiment 4a, both conditions), both the falling object and the target object were more salient than in other conditions. An argument can be made that adding a third noun just generally dilutes the #saliency of all entities, could argue it increases strain on working memory or something, so sentence focus does matter, but it inherently involves general sentence complexity as well noun order


#just looking at falling object

q4_model_falling <- lm(
  answer ~ sentence_condition,
  data = sentence_long_order_focus %>%
    filter(label_recoded=="falling object",
      sentence_condition %in% c(
      "E1",
      "4a-Focus","4a-NotFocus",
      "4c-Focus","4c-NotFocus",
      "R2-Focus","R2-NotFocus")) %>%
    mutate(sentence_condition = relevel(factor(sentence_condition), ref = "E1")))
summary(q4_model_falling)
#marginally higher ratings in 4a-Focus compared to E1,

#just looking at target object
q4_model_target <- lm(
  answer ~ sentence_condition,
  data = sentence_long_order_focus %>%
    filter(label_recoded=="target object",
      sentence_condition %in% c(
      "E1",
      "4a-Focus","4a-NotFocus",
      "4c-Focus","4c-NotFocus",
      "R2-Focus","R2-NotFocus")) %>%
    mutate(sentence_condition = relevel(factor(sentence_condition), ref = "4a-NotFocus")))

summary(q4_model_target)
# sig higher ratings in 4a-Focus compared to E1, marginal for NotFocus
```

# Plots
```{r}
#clean object names
obj_clean$object <- sub(
  "(_slice|_whole)?\\.(jpe?g|png)$|(_slice|_whole)$",
  "",
  obj_clean$object,
  ignore.case = TRUE)

#overall object rating differences (whole vs sliced)
# SUPPLEMENTAL
obj_clean %>% filter(state!="Smashed") %>%
  mutate(state = factor(state, levels = c("Whole", "Slice"))) %>%
  group_by(state) %>%
  tidyboot_mean(response, nboot = 100, na.rm = TRUE) %>%
  ggplot(aes(x = state, y = empirical_stat, fill = state)) + 
  geom_col() +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.1) +
  labs(y = "Average Typicality Rating", x = "State") +  
  theme_few()

# Looking at distribution of smashed ratings
obj_smashed <- obj_clean %>%
  filter(state == "Smashed") %>%
  mutate(object = str_sub(object, 1, -2))

obj_means <- obj_smashed %>%
  group_by(object) %>%
  tidyboot_mean(response, nboot = 100, na.rm = TRUE) %>%
  ungroup()

set.seed(1)
jwidth <- 0.5
obj_means <- obj_means %>%
  mutate(xj = 1 + runif(n(), -jwidth, jwidth))

ggplot(obj_means, aes(x = 1, y = empirical_stat)) +
  geom_violin(trim = TRUE,fill="slateblue",alpha=0.5) +
  geom_point(
    aes(x = xj, y = empirical_stat),
    size = 3
  ) +
  ggrepel::geom_text_repel(
    aes(x = xj, y = empirical_stat, label = object),
    size = 3,
    max.overlaps = Inf,
    min.segment.length = 0,
    box.padding = 0.25,
    point.padding = 0.2,
    seed = 1,
    show.legend = FALSE
  ) +
  scale_x_continuous(limits = c(0.4, 1.6)) +
  coord_cartesian(ylim = c(0, 100), clip = "off") +
  theme_few() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    plot.margin = margin(10, 40, 10, 40)
  ) +
  labs(
    x = "Item",
    y = "Average Match Rating",
    title = 'To what extent does this image match the outcome you imagined?')


# sliced
highlight_objs <- c("cheesecake", "bread", "cake", "grapefruit", "pizza")
pat <- str_c(highlight_objs, collapse = "|")

plot_df <- obj_clean %>%
  filter(state %in% c("Whole", "Slice")) %>%
  group_by(object, state) %>%
  tidyboot_mean(response, nboot = 100, na.rm = TRUE) %>%
  ungroup() %>%
  mutate(
    state = factor(state, levels = c("Whole", "Slice")),
    highlight = str_detect(str_to_lower(object), pat)
  )

ggplot(plot_df, aes(
  x = state,
  y = empirical_stat,
  group = object,
  color = highlight
)) +
  geom_line(alpha = 0.6) +
  geom_point(size = 2) +
  ggrepel::geom_text_repel(
    data = subset(plot_df, highlight & state == "Slice"),
    aes(label = object),
    size = 3,
    nudge_x = 0.15,
    show.legend = FALSE
  ) +
  scale_color_manual(
    values = c(`FALSE` = "grey20", `TRUE` = "red")
  ) +
  labs(
    x = "Object State",
    y = "Average Match Rating",
    title = ""
  ) +
  theme_few() +
  theme(legend.position = "none") +
  ylim(20, 100)


#reorder and relabel for question norming plots
exp_order <- c(
  "E1",
  "E2-Slice",
  "E2-Neut",
  "4a-Focus",
  "4a-NotFocus",
  "4c-Focus",
  "4c-NotFocus",
  "R2-Focus",
  "R2-NotFocus")

sentence_labels <- c(
  "You dropped a bowling ball on a tomato.",
  "Someone slices a tomato in front of you.",
  "Someone places a tomato in front of you.",
  "A tomato came in contact with a falling brick.",
  "A falling brick came in contact with a tomato.",
  "Onto a tomato you dropped a bowling ball.",
  "You dropped a bowling ball onto a tomato.",
  "A tomato is what you dropped a bowling ball on.",
  "A bowling ball is what you dropped on a tomato.")
  
sentence_clean_order <- sentence_clean %>%
  mutate(
    sentence_condition = factor(
      sentence_condition,
      levels = exp_order,
      labels = sentence_labels
    )
  ) %>%
  filter(!sentence_condition %in% c(
    "Someone slices a tomato in front of you.",
    "Someone places a tomato in front of you."))



q2 <- sentence_clean_order %>%
  group_by(sentence_condition) %>%
  tidyboot_mean(Q2, nboot = 100, na.rm = TRUE) %>%
  ggplot(aes(
    x = sentence_condition,
    y = empirical_stat,
    fill = sentence_condition)) + 
  geom_col() +
  geom_errorbar(
    aes(ymin = ci_lower, ymax = ci_upper),
    width = 0.1) +
  geom_text(
    aes(label = sentence_condition),
    angle = 90,
    hjust = 1.2,        # pushes text upward
    size = 3.5
  ) +
  labs(
    y = "Rating (Intact - Smashed)",
    x = "Sentence Type"
  ) +
  ggtitle("After the event described in the sentence, the object was...") +
  theme_few() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none")+ylim(0,100)


q3<- sentence_clean_order %>%
  group_by(sentence_condition) %>%
  tidyboot_mean(Q3, nboot = 100, na.rm = TRUE) %>%
  ggplot(aes(x = sentence_condition, y = empirical_stat, group = sentence_condition, fill = sentence_condition)) + 
  geom_col() +geom_text(
    aes(label = sentence_condition),
    angle = 90,
    hjust = 1.24,        # pushes text upward
    size = 3.5)+
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.1) +ggtitle("Does the sentence imply the object was...")+
  labs(y = NULL, x = "Sentence Type") +  
  theme_few() +theme(axis.text.x = element_blank(),legend.position = "none")+ylim(0,100)


#relabel for Q4
sentence_long_order <- sentence_long %>%
  mutate(
    sentence_condition = factor(
      sentence_condition,
      levels = exp_order,
      labels = sentence_labels)) %>%
  filter(!sentence_condition %in% c(
    "Someone slices a tomato in front of you.",
    "Someone places a tomato in front of you."))


q4<- sentence_long_order%>%filter(label_recoded!="you")%>%filter(!sentence_condition %in% c("A tomato is what you dropped a bowling ball on.","A bowling ball is what you dropped on a tomato."))%>%
  group_by(label_recoded,sentence_condition) %>%
  tidyboot_mean(answer, nboot = 100, na.rm = TRUE) %>%
  ggplot(aes(x = sentence_condition, y = empirical_stat, group = sentence_condition, fill = sentence_condition)) + facet_wrap(~label_recoded)+
  geom_col() +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.1) +ggtitle("How prominent was each object...")+ 
  labs(y = "Average Prominence Rating", x = "") +  
  theme_few() +theme(axis.text.x = element_blank(),legend.position = "none",strip.text = element_text(size = 14))+geom_text(
    aes(label = sentence_condition),
    angle = 90,
    hjust = 1.22,        
    size = 3)+ylim(0,100)

q2+q3

q4


```



