---
title: "object-state-changes-and squashability"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

# load packages
```{r}
library(tidyverse)
library(ggplot2)
library (ggthemes)
library(rstatix)
library(ggpubr)
library(emmeans)
library(dplyr)
library(lmerTest)
```

# import data
```{r}
prolific <- read_csv("../data/prolific_1.csv")
prolific2 <- read_csv("../data/prolific2.csv")
sona <- read_csv("../data/sona.csv")

#compare number of columns: 30 vs 31
ncol(prolific)

ncol(sona)
colnames(prolific)

colnames(sona)
#delete extra column in sona
sona <- sona %>% select(-c(sona_id))

# bind Prolific + Sona
final_data = rbind(prolific, sona)
```

# basic descriptives
```{r}
length(final_data %>% pull(subject) %>% unique())
## N(initial) = 105
## note: R counts 'NA' as a participant 
final_data %>% group_by(subject) %>% count()
sona %>% pull(subject) %>% unique()
```
# data treatment

## exclusions
```{r}
##exclude filler, practice, and non-picture trials
exclusions_data <- final_data %>%
  filter(typeoftrial=="picture" & !(trialcondition %in% c("filler", "practice"))) %>%
##calculate subject accuracy
  mutate(accuracy=ifelse(correct=="TRUE",1,0)) %>% 
  separate(trialcondition, into = c("squashability", "state"))
```

# accuracy analyses

##accuracy data
```{r}
subject_accuracy <- exclusions_data %>% group_by(subject) %>% summarise(TaskAccuracy=mean(accuracy))
InaccurateSubjects <- subject_accuracy %>% filter(TaskAccuracy < 0.8)
```

## plot
```{r}
exclusions_data %>% 
  group_by(squashability, state) %>%
   summarise(ci = list(mean_cl_boot(accuracy) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest%>%
  ggplot(aes(x= squashability, y = mean, group = state, fill = state)) +
geom_bar(stat = "identity", position = "dodge", width = 0.7, color = "gray24")+
  geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.15, 
                color = "black", position = position_dodge(0.70))+
  labs(y = "mean accuracy", title = "squashability ratings")+
  theme_clean()+
  scale_fill_manual(values = c("darksalmon", "darkslategray4","darkolivegreen4"))+
  theme(plot.background = element_rect(
    color = "white"),
    strip.text.x = element_text(size =rel(2)),
        axis.text = element_text(size =rel(1.5)),
        axis.title = element_text(size =rel(2)),
        plot.title = element_text(hjust = .5, size = rel(1.5)))
```
## main accuracy model
```{r}
acc_model = glmer(data = exclusions_data, 
                  accuracy ~ squashability + state + (1|subject) + (1|stimulus),
                  family = "binomial")
summary(acc_model)
car::Anova(acc_model)
```

# RT analyses

## rt data
```{r}
##exclude incorrect responses
rt_data <- exclusions_data %>% filter(accuracy==1) %>%
  ##exclude subjects with accuracy < 80%
  filter(!subject %in% InaccurateSubjects$subject)
##total participants after exclusion: N = 103 (2 excluded--33%, 58% accuracy)
length(rt_data %>% pull(subject) %>% unique())
```


# transforming RT
```{r}
##make rt numeric
rt_data <- rt_data %>% mutate(rt = as.numeric(rt))
## rt histogram ----does NOT look normally distributed (positive skew)
rt_data %>% filter(rt <10000) %>% ggplot(aes(x=rt)) + geom_histogram(binwidth =20, fill="pink" ) + theme_economist() + labs(x="RT (ms)", y="frequency", title= "RT histogram")
##rt log (base 10) transformation
rt_data <- rt_data %>% mutate(log10_rt=log(rt, 10))
##log10(rt) histogram
rt_data %>% ggplot(aes(x=log10_rt)) + geom_histogram(binwidth =0.1, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")
```

## MAD exclusions
```{r}
mad_data = rt_data %>%
  group_by(squashability, state) %>%
  mutate(MAD=3*mad(log10_rt), med=median(log10_rt),
         L= (med - MAD), U=(med + MAD)) %>%
  filter(log10_rt < U) %>% filter(log10_rt > L)
(nrow(data)-nrow(mad_data))/nrow(data)
```

## plot
```{r}
mad_data %>% 
  group_by(squashability, state) %>%
   summarise(ci = list(mean_cl_boot(rt) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest%>%
  ggplot(aes(x= squashability, y = mean, group = state, fill = state)) +
geom_bar(stat = "identity", position = "dodge", width = 0.7, color = "gray24")+
  geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.15, 
                color = "black", position = position_dodge(0.70))+
  labs(y = "log10(RT)", title = "RT per squashability x state condition")+
  theme_clean()+
  scale_fill_manual(values = c("darksalmon", "darkslategray4","darkolivegreen4"))+
  theme(plot.background = element_rect(
    color = "white"),
    strip.text.x = element_text(size =rel(2)),
        axis.text = element_text(size =rel(1.5)),
        axis.title = element_text(size =rel(2)),
        plot.title = element_text(hjust = .5, size = rel(1.5)))
```

## main RT model
```{r}
rt_model = lmer(data = mad_data, 
                log10_rt ~ squashability*state + (squashability |subject) + (1|stimulus))
summary(rt_model)
car::Anova(rt_model)
```

### assumptions
```{r}
library(glmmTMB)
sjPlot::plot_model(rt_model, type='diag')
sjPlot::plot_model(rt_model, type='resid')
```

### posthoc models 

```{r}
# split into picture type (state)
intact_data = mad_data %>% filter(state == "Normal")
squashed_data = mad_data %>% filter(state == "Smashed")
# run separate models on these data
intact_model = lmer(data = intact_data, log10_rt ~ squashability + (squashability | subject) + 
                      (1 | stimulus))
summary(intact_model)
car::Anova(intact_model)
squashed_model = lmer(data = squashed_data, log10_rt ~ squashability + (squashability | subject) + 
                      (1 | stimulus))
summary(squashed_model)
car::Anova(squashed_model)
```


# Demographic Info
```{r}
demo = final_data %>% filter(typeoftrial %in% c("demo", "english") & response != "0") %>%
  separate(response, into = c("demo1", "demo2", "demo3", "demo4"), sep = ":")
age = demo %>% filter(demo1 == "{\"Age\"") %>% select(demo2) %>%
  mutate(age = as.numeric(gsub("[^[:digit:] ]", "", demo2)))
age %>% summarise(mean_age = mean(age))
race = demo %>% filter(demo1 == "{\"Race\"") %>% select(demo2)
race %>% group_by(demo2) %>% count()
gender_education = demo %>% filter(demo1 == "{\"Age\"") %>% select(demo3) %>%
  separate(demo3, into = c("gender", "education"), sep = ",")  %>%
  mutate(gender = tolower(gender),
         gender = gsub("[[:space:]]", "", gender))
gender_education %>% group_by(gender) %>%
  count()
gender_education %>% group_by(education) %>%
  count()
first_lang = demo %>% filter(demo1 == "{\"English\"") %>% select(demo2)
first_lang %>% group_by(demo2) %>% count()
```

```{r}
"18-19" =(age %>% filter(c(age) <= 19 & c(age) >= 18) %>% count())
"20-29" = (age %>% filter(c(age) <= 29 & c(age) >= 20) %>% count())
"30-39" = (age %>% filter(c(age) <= 39 & c(age) >= 30) %>% count())
"40-49" = age %>% filter(c(age) <= 49 & c(age) >= 40) %>% count()
"50-59" = (age %>% filter(c(age) <= 59 & c(age) >= 50) %>% count())
"60+" = (age %>% filter(c(age) >= 60) %>% count())

```


