---
title: "descriptive/contradiction experiment"
output: html_notebook
---

# load packages
```{r}
library(tidyverse)
library(ggplot2)
library (ggthemes)
library(rstatix)
library(ggpubr)
library(emmeans)
library(dplyr)
```

# import data
```{r}
data <-read_csv('data/combined.csv')

colnames(data)
```

# basic descriptives
```{r}
## N(initial)
data %>% pull(subject) %>% unique()

## number of trials per subject
data %>% group_by(subject) %>% count()

### caution: subject 'NA' and 'subject'
```

# filtering and accuracy exclusion
```{r}
##exclude filler, practice, and non-picture trials
data <- data %>% filter(typeoftrial=="picture" & !(trialcondition %in% c("Filler", "practice_s", "practice_n")))

##calculate subject accuracy
data <- data %>% mutate(accuracy=ifelse(correct=="true",1,0))

subject_accuracy <- data %>% group_by(subject) %>% summarise(TaskAccuracy=mean(accuracy))

##exclude incorrect responses
data = data %>% filter(accuracy==1)

##exclude subjects with accuracy < 60%
InaccurateSubjects <- subject_accuracy %>% filter(TaskAccuracy < 0.6)

data2 <- data %>% filter(!subject %in% InaccurateSubjects$subject) 

##total participants after exclusion: N=
data2 %>% pull(subject) %>% unique()
```

# log10 transformation and histograms
```{r}
data2 <- data2 %>% mutate(rt = as.numeric(rt)) %>% mutate(log10_rt=log(rt, 10))

data2 %>% filter(rt <10000) %>% ggplot(aes(x=rt)) + geom_histogram(binwidth =20, fill="pink" ) + theme_economist() + labs(x="RT (ms)", y="frequency", title= "RT histogram")

data2 %>% ggplot(aes(x=log10_rt)) + geom_histogram(binwidth =0.1, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")
```

# subject means
```{r}
####WARNING: THE SEPARRATORS IN TYPEOFTRIAL ARE INCONSISTENT in the original data THE FIRST TWO LINES of this chunk FIX THIS

data2_split <- data2 %>% separate(trialcondition, into = c("weight", "causal_result"))
data2 <- data2_split %>% unite(col="trialcondition", c(weight, causal_result), sep = "_")

subject_means <- data2 %>% group_by(subject, trialcondition) %>% summarise(subj_meanLog=mean(log10_rt), subj_meanRT=mean(rt))
```

# outliers
```{r}
outliers <- subject_means %>% group_by(trialcondition) %>% identify_outliers(subj_meanLog)

outlier_exclusion <- outliers %>% filter(is.extreme=="TRUE")

subject_means <- subject_means %>% filter(!subject %in% outlier_exclusion)
```

# condition means, SEM calculation
```{r}
condition_meansRT <- subject_means %>% group_by(trialcondition) %>% summarise(mean=mean(subj_meanRT), sd=sd(subj_meanRT)) 

n= subject_means %>% group_by(subject) %>% n_groups() 

condition_meansRT <- condition_meansRT %>% mutate(SEM=sd/sqrt(n))
```

# graph
```{r}
condition_meansRT %>% separate(trialcondition, into = c("weight","causal_result"), sep="_") %>% ggplot(aes(x=causal_result, y=mean, fill=weight)) + geom_col(position = "dodge") +  labs(x="expectedness of picture shape", y="RT (ms)", title = "the effect of contradictory situation descriptors on picture verification time") + geom_errorbar(aes(ymin= (mean - SEM), ymax= (mean + SEM)), width=.25, position=position_dodge(width=0.9)) + theme_economist_white() + scale_fill_economist()

ggsave("contradictions_graph.jpeg")
```
```

```{r}

```


