---
title: "slicing experiment"
output:
  word_document: default
  html_document:
    df_print: paged
---

# load packages
```{r}
library(tidyverse)
library(ggplot2)
library (ggthemes)
library(rstatix)
library(ggpubr)
library(emmeans)
library(dplyr)
```

# import & bind data
```{r}
## read sona and prolific data

prolific_data <- read_csv('../data/prolific_data.csv')
sona_data <- read_csv('../data/sona_data.csv') 
prolific_data_2 <- read_csv('../data/slicing_data2.csv')

ncol(prolific_data)
ncol(sona_data)
ncol(prolific_data_2)

colnames(prolific_data)
colnames(sona_data)
colnames(prolific_data_2)

## remove extra col.s and problematic col.
sona_data <- sona_data %>% select(!c(sona_id, subject_id, recorded_at))
prolific_data <- prolific_data %>% select(!c(subject_id, recorded_at))
prolific_data_2 <- prolific_data_2 %>% select(!c(recorded_at))

##bind prolific & sona data
data <- rbind(prolific_data, sona_data, prolific_data_2)
```

# basic descriptives
```{r}
## N(initial)
data %>% pull(subject) %>% unique()

## number of trials per subject: N(initial) = 106
data %>% group_by(subject) %>% count()

### caution: subject 'NA'
```

# filtering and accuracy exclusion
```{r}
##exclude filler, practice, and non-picture trials
data <- data %>% filter(typeoftrial=="picture" & !(trialcondition %in% c("filler", "practice")))

##calculate subject accuracy
data <- data %>% mutate(accuracy=ifelse(correct=="TRUE",1,0))

subject_accuracy <- data %>% group_by(subject) %>%
      summarise(TaskAccuracy=mean(accuracy))

##exclude incorrect responses
data = data %>% filter(accuracy==1)

##exclude subjects with accuracy < 60% & incorrect responses
InaccurateSubjects <- subject_accuracy %>% filter(TaskAccuracy < 0.6)

data2 = data %>% filter(!subject %in% InaccurateSubjects$subject) 

##total participants after exclusion: N = 98
data2 %>% pull(subject) %>% unique()
```

# log10 transformation & histograms
```{r}
data2 <- data2 %>% mutate(rt = as.numeric(rt)) %>% mutate(log10_rt=log(rt, 10))

data2 %>% filter(rt <10000) %>% ggplot(aes(x=rt)) + geom_histogram(binwidth =20, fill="pink" ) + theme_economist() + labs(x="RT (ms)", y="frequency", title= "RT histogram")

data2 %>% ggplot(aes(x=log10_rt)) + geom_histogram(binwidth =0.1, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")
```

# subject means
```{r}
subject_means <- data2 %>% group_by(subject, trialcondition) %>% summarise(subj_meanLog=mean(log10_rt), subj_meanRT=mean(rt)) 
```


# outliers (3x IQR)
```{r}
##outliers <- subject_means %>% group_by(trialcondition) %>% identify_outliers(subj_meanLog)

##outlier_exclusion <- outliers %>% filter(is.extreme=="TRUE")
##outlier_exclusion <- outliers

##subject_means <- subject_means %>% filter(!subject %in% outlier_exclusion)
## 1 extreme outlier removed > N = 97

## subject_means <- subject_means %>% filter(!subject %in% outliers)

##final_outliers = outlier_exclusion$subject
```

#outliers (3xMAD)
```{r}
MADtable <- data2 %>% select(c(7,9,26,31))

trial_table <- MADtable %>% unite("trial_id", 1:2)

a = trial_table %>% filter(trialcondition =="neutral-whole") %>% mutate(MAD=3*mad(log10_rt), med=median(log10_rt))
b= trial_table %>% filter(trialcondition =="neutral-slice") %>% mutate(MAD=3*mad(log10_rt), med=median(log10_rt))
c= trial_table %>% filter(trialcondition =="modified-whole") %>% mutate(MAD=3*mad(log10_rt), med=median(log10_rt))
d= trial_table %>% filter(trialcondition =="modified-slice") %>% mutate(MAD=3*mad(log10_rt), med=median(log10_rt))

## Note these are all 3*MAD
a = a %>% mutate(L= (med - MAD), U=(med + MAD))
b=b %>% mutate(L= (med - MAD), U=(med + MAD))
c=c %>% mutate(L= (med - MAD), U=(med + MAD))
d=d %>% mutate(L= (med - MAD), U=(med + MAD))

data3 <- rbind(a,b,c,d)

outliers <- data3 %>% filter((log10_rt > U) | (log10_rt < L))

dataS <- data2

data2 <- data2 %>% unite("trial_id", c(7,9), sep="_")

data2 <- data2 %>% filter(!trial_id %in% outliers$trial_id)

data2 <- data2 %>% separate(trial_id, into = c("subject", "trial_index"), sep="_")
```

# plot
```{r}
data2 = data2 %>% separate(trialcondition, into = c("sentence", "picture"), sep="-") 
data2 %>% 
  group_by(sentence, picture) %>%
  summarise(ci = list(mean_cl_boot(rt) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest%>%
  ggplot(aes(x= sentence, y = mean, group = picture, fill = picture)) +
geom_bar(stat = "identity", position = "dodge", width = 0.7, color = "gray24")+
  geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.15, 
                color = "black", position = position_dodge(0.70))+
  labs(y = "mean rt", title = "sentence type")+
  theme_clean()+
  scale_fill_manual(values = c("darksalmon", "darkslategray4","darkolivegreen4"))+
  theme(plot.background = element_rect(
    color = "white"),
    strip.text.x = element_text(size =rel(2)),
        axis.text = element_text(size =rel(1.5)),
        axis.title = element_text(size =rel(2)),
        plot.title = element_text(hjust = .5, size = rel(1.5)))
```

```{r}
data2 %>% group_by(sentence, picture) %>% shapiro_test(log10_rt)

##qqplot
ggqqplot(data2, "log10_rt", ggtheme = theme_bw()) + facet_grid(sentence ~ picture, labeller = "label_both")
```


# model
```{r}
library(lmerTest)
rt_model = lmer(data = data2, log10_rt ~ sentence*picture + (1|subject) + (1|stimulus))
summary(rt_model)
car::Anova(rt_model)
```

# assumptions
```{r}
sjPlot::plot_model(rt_model, type='diag')
sjPlot::plot_model(rt_model, type='resid')
```

# condition means, SEM calculation
```{r}
condition_meansRT <- subject_means %>% group_by(trialcondition) %>% summarise(mean=mean(subj_meanRT), sd=sd(subj_meanRT)) 

n= subject_means %>% group_by(subject) %>% n_groups() 

condition_meansRT <- condition_meansRT %>% mutate(SEM=sd/sqrt(n))
```

# graph
```{r}
condition_meansRT %>% separate(trialcondition, into = c("sentence_type","picture_type"), sep="-") %>% ggplot(aes(x=picture_type, y=mean, fill=sentence_type)) + geom_col(position = "dodge") +  labs(x="picture type", y="RT (ms)", title = "RT interaction of picture and sentence type") + geom_errorbar(aes(ymin= (mean - SEM), ymax= (mean + SEM)), width=.25, position=position_dodge(width=0.9)) + theme_economist_white() + scale_fill_economist()

ggsave("slicing_graph1.jpeg")
```

```{r}
subject_means_split <- subject_means %>% separate(trialcondition, into=c("sentence","picture"), sep="-")

subject_means_split <- subject_means_split %>% ungroup() 

RManova <- anova_test(data = subject_means_split, dv=subj_meanLog, wid = subject, within = c(sentence, picture), effect.size = "pes")
get_anova_table(RManova)
```
# conduct post-hoc tests (if needed)
```{r}
##decomposing significant interaction

subject_means_split %>% group_by(picture) %>% anova_test(dv=subj_meanLog, wid = subject, within = sentence, effect.size = "pes") %>% get_anova_table() %>% adjust_pvalue(method = "bonferroni")
```

# normality
```{r}
##shapiro test
subject_means %>% group_by(trialcondition) %>% shapiro_test(subj_meanLog)

ggqqplot(subject_means_split, "subj_meanLog", ggtheme = theme_bw()) + facet_grid(sentence ~ picture, labeller = "label_both")

subject_means %>% filter(trialcondition=="modified-slice") %>% ggplot(aes(x=subj_meanLog)) + geom_histogram(binwidth =0.05, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")

subject_means %>% filter(trialcondition=="modified-whole") %>% ggplot(aes(x=subj_meanLog)) + geom_histogram(binwidth =0.05, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")

subject_means %>% filter(trialcondition=="neutral-slice") %>% ggplot(aes(x=subj_meanLog)) + geom_histogram(binwidth =0.05, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")

subject_means %>% filter(trialcondition=="neutral-whole") %>% ggplot(aes(x=subj_meanLog)) + geom_histogram(binwidth =0.05, fill="pink" ) + theme_economist() + labs(x="log10(rt)", y="frequency", title= "RT histogram")
```
