---
title: "Object State Sanity Check"
author: "Channing Hambric"
date: "2024-12-02"
output: html_document
---


# load packages
```{r}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(dplyr)
library(stringr)
```

# import data
```{r}
#Data from pilot - N=2
check_data <-read.csv("../data/squashability_check.csv", fileEncoding = "UTF-8")

base<-check_data
```

#participant counts
```{r}
check_data_clean <- check_data %>% 
  filter(!is.na(subject))

length(check_data_clean %>% pull(subject_id) %>%unique())

#Should be 2 participants
```
#DESIGN:

Practice - 4 trials total, 2 y, 2 n

Experimental Trials - 24 target trials, 24 filler trials
Squashable_Squashed
Squashable-Normal
Unsquashable-Squashed
Unsquashable-Normal


#checking practice
```{r}
prac_data <- check_data %>%
  filter(trialcondition=="practice") %>% filter(correct!="NA")

#Each participant should get 4 practice, 2 with yes (true) as the correct answer and 2 with no (False)
prac_data %>% group_by(subject,trialcondition,response,correct) %>% count()


```


#checking experimental trials
```{r}
exp_data <- check_data %>%
  filter(typeoftrial=="picture" & !(trialcondition %in% c("filler", "practice"))) %>%
  separate(trialcondition, into = c("squashability", "state"))

#There should be 48 trials total (2 sub x 24)
exp_data %>% count()

#There should be 24 trials per participant
exp_data %>% group_by(subject) %>% count()

#Each participant should have 12 trials in each state condition
exp_data %>% group_by(subject, state) %>% count()

#Each participant should have 12 trials in each squashability condition
exp_data %>% group_by(subject, squashability) %>% count()

#Each participant should have 6 trials in each squashability x state condition
exp_data %>% group_by(subject, squashability, state) %>% count()

#Across participants, there should be 12 trials in each squasahability x state condition (2 sub x 6 trials)
exp_data %>% group_by(squashability, state) %>% count()


#Commenting out since not all conditions sampled
#Each item should appear in each  of 8 conditions across lists

#items <- gsub('.{0,5}$', '', exp_data$object) %>% as.data.frame()
#exp_data <- exp_data %>% mutate(item = items[,1] )

#exp_data %>%
#  select(item, weight, state, focus) %>% unique() %>%
#  group_by(item) %>% arrange(item) %>%
#  summarise(count = n()) %>%  
#  mutate(status = case_when(
#    count < 8 ~ "item does not appear in all conditions",
#    count == 8 ~ "item appears in all conditions"
#  ))


#Checking that list corresponds to condition
exp_data %>%select(condition,list_number) %>%unique()

#Checking that all normal/smashed pictures were labeled as such
lab_data <- exp_data %>%
  mutate(check_state = str_sub(stimulus, -6), 
         label = case_when(
           (check_state %in% c("S.jpeg","S.png") & state == "Smashed") ~ TRUE,  
           (check_state %in% c("N.jpeg","N.png") & state == "Normal") ~ TRUE,  
           TRUE ~ FALSE  
         )) %>% select(check_state,stimulus,state,label)

if (all(lab_data$label == TRUE)) {
  print("all images labeled correctly")
} else {
  print("Some images mislabeled")
}

```

#checking filler
```{r}
filler_data <- check_data %>%
  filter(trialcondition=="filler") %>% filter(correct %in% c("TRUE","FALSE"))

#There should be 48 total (2 sub x 24 trials)
filler_data %>% count()

#There should be 24 trials per participant
filler_data %>% group_by(subject) %>% count()

```






