---
title: "R Notebook"
output: html_notebook
---

# load packages
```{r}
library(tidyverse)
library(ggplot2)
library (ggthemes)
library(rstatix)
library(ggpubr)
library(emmeans)
library(dplyr)
```

# import data
```{r}

###change to actual data
data <- read_csv("Normative_Pilot_Data.csv")
```

# tidy data
```{r}
data <- data %>% filter(Finished==1) %>% select(c(6,7,9,16,18:49))

####change this for the actual data
data <- data %>% filter(DistributionChannel=="preview")

data <- data %>% rename(duration = `Duration (in seconds)`)
```

# survey duration outliers
```{r}
data <- data %>% mutate(duration = as.numeric(duration))

outliers <- data %>% identify_outliers(duration)
extreme_outliers <- outliers %>% filter(is.extreme=="TRUE")
data_trimmed <- data %>% filter(!ResponseId %in% extreme_outliers)
```

# make data long
```{r}
data_long <- data_trimmed %>% select(-c(1,2,4)) %>% pivot_longer(names_to = "condition...item", cols = 'U...18':'F...49')
```

# create condition column
```{r}
data_long <- data_long %>% separate(condition...item, into=c("condition","item") )
```

# Group Differences
```{r}
data_long <- data_long %>% mutate(value = as.numeric(value))

##subject and condition means, sd, sem
subject_means <- data_long %>% group_by(ResponseId, condition) %>% summarise(subj_mean = mean(value))

condition_data <- subject_means %>% group_by(condition) %>% summarise(mean_response = mean(subj_mean), sd=sd(subj_mean))
n= subject_means %>% group_by(ResponseId) %>% n_groups() 
condition_data <- condition_data %>% mutate(SEM = sd/sqrt(n))

## Plot and ANOVA
condition_data %>%  ggplot(aes(x=condition, y=mean_response)) + geom_col(position = "dodge") +  labs(x="object squashability", y="squashable rating (1-not at all -- 5-extremely)", title = "Squashable ratings of experimental item conditions") + geom_errorbar(aes(ymin= (mean_response - SEM), ymax= (mean_response + SEM)), width=.25, position=position_dodge(width=0.9)) + theme_economist_white() + scale_fill_economist()

subject_means %>% group_by(condition) %>% shapiro_test(subj_mean)

subject_outliers <- subject_means %>% group_by(condition) %>% identify_outliers(subj_mean)
extreme_subject_outliers <- subject_outliers %>% filter(is.extreme=="TRUE")
subjects_trimmed <- subject_means %>% filter(!ResponseId %in% extreme_outliers)

subjects_trimmed <- subjects_trimmed %>% ungroup() 


get_anova_table(RManova)
```

# t-tests
```{r}
U <- data_long %>% filter(condition == "U")
S <- data_long %>% filter(condition == "S")

Uitem_mean <- U %>% group_by(item) %>% summarize(mean_item = mean(value))
Sitem_mean <- S %>% group_by(item) %>% summarize(mean_item = mean(value))

shapiro.test(Uitem_mean$mean_item)
shapiro.test(Sitem_mean$mean_item)

ggqqplot(Uitem_mean$mean_item, ylab = "value",
         ggtheme = theme_minimal())
ggqqplot(Sitem_mean$mean_item, ylab = "value",
         ggtheme = theme_minimal())

uttest <- t.test(Uitem_mean$mean_item, mu = 3, alternative = "less")
sttest <- t.test(Sitem_mean$mean_item, mu = 3, alternative = "greater")

uttest
sttest

before <- Uitem_mean$mean_item
after <- Sitem_mean$mean_item

UxSttest = t.test(before,after, paired = TRUE)
UxSttest




```

